### ISSUE TITLE
Update circles frontend to latest version

### ISSUE THREAD

**Issue by Hamdy** [threefoldtech/Threefold-Circles-front#7]
we need to use latest version of `taiga` to work with the latest circles backend
we use for now temporary repos :
https://github.com/threefoldtech/taiga-frontend
https://github.com/threefoldtech/taiga-backend

The goal is to have a version of circles-front 
we need to follow these easy steps

- [x] 3 bot login integration (make front end works with backend)  no re branding at this point
- [x] logo

**Comment by samaradel** [comment]
Threebot login added
